site_name: Corona2
repo_url: https://github.com/topcoderinc/corona2
pages:
    - 'Project Docs and links':
      - 'Corona2': index.md
      - cnn: 'tcprojwrapper.md'
    - 'Topcoder Docs':
       - tcProjWrapper: tcprojwrapper.md
       - 'Copilot Responsibilities': topcoder/copilotsResponsiblites.md
       - code:
          - 'Fixing Bugs from github': topcoder/fixingBugs.md
          - 'Ragnar: Git Process': topcoder/RagnarGit.md
theme_dir: cinder/site
